source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TargetActionDemo' do

	pod 'YYModel', '~> 1.0.4'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MJRefresh', '~> 3.4.1'
  pod 'OCMock', '~> 3.6'
  
end

target 'TargetActionDemoTests' do
  pod 'YYModel', '~> 1.0.4'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MJRefresh', '~> 3.4.1'
  pod 'OCMock', '~> 3.6'
end
